version: '2'

services:
  nginx:
    build:
      context: ./
      dockerfile: docker/Dockerfile
    volumes:
      - ./build:/usr/share/nginx/html/home
    networks:
      vpcbr:
        ipv4_address: 10.11.0.5
    restart: always

networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 10.11.0.0/16
         gateway: 10.11.0.1
